### ISSUE TITLE
Unclear distinction

### ISSUE THREAD

**Issue by oxidist** [riceissa/ama#1]
> it’s easier to learn a new thing than learn a specific new thing; this is the de re vs de dicto distinction. “it’s easier to learn something (de dicto) than to learn something (de re)”.

what did you mean by this?

**Comment by riceissa** [comment]
What I meant is that I could have a mindset like "I'm going to learn linear algebra this month, and will spend all my learning time on linear algebra" ("learn a specific new thing", de re) or I could have a mindset like "I'm going to learn some unspecified new thing each day, whatever it may be, depending on what I feel curious about on each day" ("learn a new thing", de dicto). I've found the latter to be much more enjoyable/easy for me.

The connection with the de re vs de dicto terminology is that if I just say "Bob is going to learn something new today", it isn't immediately clear whether Bob has a specific thing in mind, just like in the [Wikipedia article](https://en.wikipedia.org/wiki/De_dicto_and_de_re) sentences like "Peter believes someone is out to get him" or "Jana wants to marry the tallest man in Fulsom County" don't make it clear whether Peter or Jana has a specific someone in mind.

(I'm closing the issue just to make it clear to myself that I've answered the question, but feel free to reply if something still isn't clear.)
